kind: Pod
apiVersion: v1
metadata:
  name: nfs-provisioner
spec:
  containers:
  - name: nfs-provisioner
    image: wongma7/nfs-provisioner:latest
    ports:
      - name: nfs
        containerPort: 2049
      - name: mountd
        containerPort: 20048
      - name: rpcbind
        containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: nfs-provisioner-exports

