kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-provisioner-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      containers:
        - name: nfs-provisioner
          image: wongma7/nfs-provisioner
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          args:
            - "-provisioner=matthew/nfs"
          env:
            - name: MY_SERVICE_NAME
              value: nfs-provisioner
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /srv
      nodeSelector:
        nfs-server: yep
