kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: matthew-nfs
    spec:
      containers:
        - name: nfs-provisioner
          image: wongma7/nfs-provisioner
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - DAC_READ_SEARCH
          args:
            - "-provisioner=matthew/nfs"
          env:
            - name: MY_SERVICE_NAME
              value: nfs-provisioner
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: export-volume
              mountPath: /export
            - name: podinfo
              mountPath: /podinfo
              readOnly: false
      volumes:
        - name: export-volume
          hostPath:
            path: /srv
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
      nodeSelector:
        app: matthew-nfs
