kind: Pod
apiVersion: v1
metadata:
  name: nfs-provisioner
spec:
  containers:
    - name: nfs-provisioner
      image: wongma7/nfs-provisioner
      ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        - name: rpcbind-udp
          containerPort: 111
          protocol: UDP
      securityContext:
        privileged: true
      args:
        - "-provisioner=matthew/nfs"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - name: podinfo
          mountPath: /podinfo
          readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
