kind: Service
apiVersion: v1
metadata:
  name: nfs-provisioner
spec:
  selector:
    app: matthew-nfs
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
